name: TestNote By Ebenezer

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  build:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust to your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust to your requirements file location

    - name: Run tests
      run: python manage.py test  # Adjust to your Django management command

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/test-results.xml'  # Adjust to your test results file location